<?php
class BaseClass {
    protected $name = "BaseClass";
    public function __construct()
    {
        print("In " . $this->name . "constructor<br>");
    }
    public function __destruct()
    {
        // TODO: Implement __destruct() method.
        print("Destroying " . $this->name . "<br>");
    }
}

class SubClass extends BaseClass {
    public function __construct()
    {
        $this->name = "SubClass";
        parent::__construct();
    }
    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }
}
//$obj1= new SubClass();
$obj2= new BaseClass();